[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"
authors = ["Quan Hua <quanhua92@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
